---
title: "Wine of The World"
author: "Vincent Guillemot & Hervé Abdi & Ju-Chi Yu & Soudeh Ardestani Khoubrouy"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Wine of The World}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = TRUE, 
  dev = "svg",
  fig.ext = "svg"
)
library(dplyr)
library(knitr)
library(kableExtra)
library(ggplot2)
library(TExPosition)
```

## Load the data

With the following command

```{r winesOf3Colors}
data("winesOf3Colors", package = "data4PCCAR")
```

```{r hidden colors, echo = FALSE}
wineColors <- winesOf3Colors$winesDescriptors$color
wineColors <- as.character(recode(wineColors, red = 'indianred4', 
                white = 'gold', rose = 'lightpink2'))
```

## Two tables with descriptors and other supplementary information

### Two data tables {.smaller}

```{r four table, echo = FALSE}
descr <- winesOf3Colors$winesDescriptors %>% 
    select(origin, color, varietal)
suppl <- winesOf3Colors$winesDescriptors %>% 
    select(Price)
chemi <- winesOf3Colors$winesDescriptors %>% 
    select(Acidity, Alcohol, Sugar, Tannin)
senso <- winesOf3Colors$winesDescriptors %>% 
    select(fruity, floral, vegetal, 
           spicy, woody, sweet, astringent, 
           hedonic)
```

```{r tab, echo = FALSE, results='asis'}
fontsize <- 9.

chemi %>%
    kable("html", caption = "Table 1: Chemical data") %>%
    kable_styling("striped", position = "float_left", full_width = F)  %>%
    row_spec(1:nrow(chemi), 
    font_size = fontsize) %>%
    row_spec(0, angle = 0, align = "right", font_size = fontsize)

senso %>%
    kable("html", caption = "Table 2: Sensory data") %>%
    kable_styling("striped", position = "left", full_width = F)  %>%
    row_spec(1:nrow(senso), 
    font_size = fontsize) %>%
    row_spec(0, angle = 0, align = "right", font_size = fontsize)

```

### Descriptors and supplementary variable {.smaller}

* Descriptors: `origin`, `color` and `varietal`;
* Suplementary variables: `Price`;
 
## Do PLS

```{r}
res.tesPLS <- tepPLS(chemi, senso, DESIGN = descr$color, graphs = FALSE)

## generate figures
res.tesPLS.fig <- coreTTAplot()
```

### Correlation between the two tables

```{r}

```


### Scree plot

### Latent variables

### Loadings

### Circles of correlations

