---
title: "A Sensory Data Set on Chewing-gums"
author: "Vincent Guillemot & Hervé Abdi & Ju-Chi Yu & Soudeh Ardestani Khoubrouy"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{A Sensory Data Set on Chewing-gums}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = TRUE, 
  dev = "svg",
  fig.ext = "svg"
)
library(dplyr)
library(knitr)
library(kableExtra)
library(ggplot2)
```

## Load the data

With the following command

```{r winesOf3Colors}
data("sixteenGums4Descriptors", package = "data4PCCAR")
```

```{r hidden colors, echo = FALSE}
chgu <- sixteenGums4Descriptors$ratingsIntensity
chguColors <- sixteenGums4Descriptors$color4Products
descColors <- sixteenGums4Descriptors$color4Descriptors
```

## The Products {.smaller}

```{r chgu, echo = FALSE, results='asis'}
fontsize <- 9
chgu %>%
    kable("html") %>%
    kable_styling("striped", full_width = F)  %>%
    row_spec(1:nrow(chgu),
             font_size = fontsize) %>%
    row_spec(0, angle = 0, align = "right", font_size = fontsize)
```


## The ratings


```{r ratings, echo = FALSE, fig.width = 5, fig.height = 8}
chgu_long <- tibble(
    yids = rownames(chgu), 
    as_tibble(scale(chgu))) %>%
    tidyr::pivot_longer(
        -yids,
        values_to = "scores",
        names_to = "xids")


(suppressWarnings(heatmap.rxy <- chgu_long  %>%
    ggplot(aes(xids, yids, fill = scores)) +
    geom_tile() +
    # geom_text(aes(label = round(scores, 2))) +
    scale_fill_gradient2() +
    theme_bw() +
    theme(
        axis.ticks.y = element_line(color = chguColors),
        axis.text.y = element_text(color = chguColors, size = 7),
        axis.ticks.x = element_line(color = descColors),
        axis.text.x = element_text(color = descColors, size = 7),
    ) +
    labs(x = "", y = ""))) + 
    theme(legend.position = "bottom")
```


